# Generated by Django 5.1.1 on 2024-10-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snickers',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
    ]
